### ISSUE TITLE
Rdio Player Doesn't Properly Stop

### ISSUE THREAD

**Issue by dasevilla** [rdio/api#8] opened 2012-10-31 20:18 UTC
[Original topic](https://groups.google.com/d/msg/rdio-api/-/aX31BxgNZqkJ):

> If you have an Rdio player that is seeking to a position then you call stop & try to play another source, the player will often wind up playing both songs with no way of stopping the first song.
> 
> For example:
> [self.rdio.player playSource:@"11111111"];
> ...wait a few seconds...
> [self.rdio.player seekToPosition:30];
> ...wait a few seconds...
> [self.rdio.player stop];
> [self.rdio.player playSource:@"22222222"];

**Comment by bendytree** [comment] 2012-11-01 19:22
Hi Devin -

Thanks for migrating the issue here. [Here is a simple example project](http://dl.dropbox.com/u/2505719/rdio-audio-wont-stop.zip) in case that helps.

Josh

**Comment by bendytree** [comment] 2012-11-05 16:35
Devin -

Have you all had any luck figuring this out?  We'd love to release a fix in our app as soon as possible.

Side question: Is there any way of streaming from Rdio without using the rdio-ios library? For example, using the authenticated token to get a temporary URL for streaming the mp3 so we could use our own audio player within the app?  Or is the rdio-ios library open source anywhere where we could help out?

Josh

**Comment by rknLA** [comment] 2012-11-07 00:32
Hi Josh,

Today's my first day at Rdio and I've been looking into this.  I've been able to reproduce the issue using your sample code in a few ways, and I'm working on a fix.  Part of the issue is that seeking happens somewhat asynchronously, so the seek isn't guaranteed to be complete by the time you're executing the `stop` instruction.

While I work on fixing that, can I ask what your use case is?  It's possible that it'll be more time effective for you if we can figure out a work-around while the bug fixes go through code review.

Best,
Kevin

**Comment by bendytree** [comment] 2012-11-07 00:53
Hi Kevin -

Thanks for getting back with me. It took us a while to pin down the problem in a reproducible form, but here's how the bug normally plays out when someone is using our app.

1) They play, then pause a song
2) Then they use a slider to seek to another part of the song
3) Maybe they lose interest, maybe it's taking too long to restart playing, but either way they wind up deciding to move on to another song
4) The seeking song finally starts playing and is unstoppable 

I know it may not seem like a huge deal, but it puts the app in a position where there is absolutely no way for the listener to stop the song. Most listeners report that they opted to uninstalling the app to get the song to stop. 

Josh

**Comment by rknLA** [comment] 2012-11-07 03:41
Hey Josh,

I was actually able to reproduce this bug in the Rdio iPhone app as well, but I'm fairly certain that the fix I came up with is sufficient.  I'll see if we can do a code review tomorrow morning to get the fix released ASAP.

Thanks for unearthing this!
Kevin

**Comment by rknLA** [comment] 2012-11-09 00:09
Should be fixed in the latest release of the [iOS SDK](http://www.rdio.com/media/static/developer/ios/rdio-ios.tar.gz).

**Closed as completed by rknLA** 2012-11-09 00:09 UTC
Labels: bug, ios sdk
